arb-dir: lib/src/l10n
template-arb-file: app_en.arb
output-dir: lib/src/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - hi
  - bn
  - te
  - mr
  - ta
  - ur
  - gu
  - ml
  - kn
  - or
