arb-dir: lib/src/core/l10n
template-arb-file: app_en.arb
output-dir: lib/src/core/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: build/untranslated_messages.json
preferred-supported-locales:
  - en
  - hi
  - bn
  - te
  - mr
  - ta
  - ur
  - gu
  - ml
  - kn
  - or
